# CMake generated Testfile for 
# Source directory: /src/tests/vertex
# Build directory: /src/docker_build/tests/vertex
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[vertex/gen-input]=] "/src/docker_build/python_venv/bin/python" "create-test-input.py" "false")
set_tests_properties([=[vertex/gen-input]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_SETUP "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;20;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/pos-hdf5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-hdf5" "1" "st")
set_tests_properties([=[vertex/pos-hdf5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/pos-hdf5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-hdf5" "4" "mt")
set_tests_properties([=[vertex-mt/pos-hdf5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/pos-hdf5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-hdf5" "4" "mp")
set_tests_properties([=[vertex-mp/pos-hdf5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/pos-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-lh5" "1" "st")
set_tests_properties([=[vertex/pos-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/pos-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-lh5" "4" "mt")
set_tests_properties([=[vertex-mt/pos-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/pos-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-lh5" "4" "mp")
set_tests_properties([=[vertex-mp/pos-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/pos-lh5-mm]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-lh5-mm" "1" "st")
set_tests_properties([=[vertex/pos-lh5-mm]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/pos-lh5-mm]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-lh5-mm" "4" "mt")
set_tests_properties([=[vertex-mt/pos-lh5-mm]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/pos-lh5-mm]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-lh5-mm" "4" "mp")
set_tests_properties([=[vertex-mp/pos-lh5-mm]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/kin-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin-lh5" "1" "st")
set_tests_properties([=[vertex/kin-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/kin-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin-lh5" "4" "mt")
set_tests_properties([=[vertex-mt/kin-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/kin-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin-lh5" "4" "mp")
set_tests_properties([=[vertex-mp/kin-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/kin-hdf5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin-hdf5" "1" "st")
set_tests_properties([=[vertex/kin-hdf5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/kin-hdf5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin-hdf5" "4" "mt")
set_tests_properties([=[vertex-mt/kin-hdf5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/kin-hdf5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin-hdf5" "4" "mp")
set_tests_properties([=[vertex-mp/kin-hdf5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/kin2-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin2-lh5" "1" "st")
set_tests_properties([=[vertex/kin2-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/kin2-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin2-lh5" "4" "mt")
set_tests_properties([=[vertex-mt/kin2-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/kin2-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "kin2-lh5" "4" "mp")
set_tests_properties([=[vertex-mp/kin2-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/pos-kin-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-kin-lh5" "1" "st")
set_tests_properties([=[vertex/pos-kin-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/pos-kin-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-kin-lh5" "4" "mt")
set_tests_properties([=[vertex-mt/pos-kin-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/pos-kin-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-kin-lh5" "4" "mp")
set_tests_properties([=[vertex-mp/pos-kin-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex/pos-kin-combined-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-kin-combined-lh5" "1" "st")
set_tests_properties([=[vertex/pos-kin-combined-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "extra" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;34;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mt/pos-kin-combined-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-kin-combined-lh5" "4" "mt")
set_tests_properties([=[vertex-mt/pos-kin-combined-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;38;add_test;/src/tests/vertex/CMakeLists.txt;0;")
add_test([=[vertex-mp/pos-kin-combined-lh5]=] "/src/docker_build/python_venv/bin/python" "run-vtx.py" "pos-kin-combined-lh5" "4" "mp")
set_tests_properties([=[vertex-mp/pos-kin-combined-lh5]=] PROPERTIES  ENVIRONMENT_MODIFICATION "MPLCONFIGDIR=set:/src/tests;RMG_STATS_FACTOR=set:1" FIXTURES_REQUIRED "vertex-input-fixture" LABELS "mt;extra" PROCESSORS "4" _BACKTRACE_TRIPLES "/src/tests/vertex/CMakeLists.txt;42;add_test;/src/tests/vertex/CMakeLists.txt;0;")
