format:
  line_width: 99

# Causes a few issues - can be solved later, possibly.
markup:
  enable_markup: false

lint:
  disabled_codes: ["C0111", "C0113"]
  argument_var_pattern: "[a-zA-Z_][a-zA-Z0-9_]+"
  public_var_pattern: "[A-Z][A-Za-z0-9_]+"
  private_var_pattern: "[a-zA-Z_][A-Za-z0-9_]+"
