version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout: # for setuptools_scm to work correctly.
      - git fetch --unshallow || true
    pre_build: # prepare Doxyfile, run Doxygen, prepare Sphinx
      - export DOXYGEN_DOT_PATH=$(which dot)
      - sed s/@DOXYGEN_INPUT_DIR@/../g\;s/@DOXYGEN_OUTPUT_DIR@/_doxygen/g
        docs/Doxyfile.in > docs/Doxyfile
      - cat docs/Doxyfile
      - cd docs && doxygen
      - mkdir -p docs/extra/doxygen
      - cp -r docs/_doxygen/html/* docs/extra/doxygen
      - cp docs/conf.py.in docs/conf.py
      # this is necessary to preserve versions from git tags. I don't know what writes to this file before building. wtf!!
      - git restore docs/environment.yml

conda:
  environment: docs/environment.yml
