# set the seed to a value that produced enough events in output files, so that we don't
# have to generate high statistics for all ntuples to be filled.
/RMG/Manager/Randomization/Seed 1403045780

/RMG/Geometry/GDMLDisableOverlapCheck true

/RMG/Geometry/RegisterDetector Germanium det1 11
/RMG/Geometry/RegisterDetector Germanium det2 12

/run/initialize

/RMG/Manager/Logging/LogLevel detail

/RMG/Output/Vertex/StorePrimaryParticleInformation true
