/RMG/Geometry/RegisterDetector Scintillator scint1 1
/RMG/Geometry/RegisterDetector Scintillator scint2 2
/RMG/Geometry/RegisterDetector Germanium det1 11
/RMG/Geometry/RegisterDetector Germanium det2 12

/RMG/Output/ActivateOutputScheme Track

/control/execute macros/_init.mac

/RMG/Output/NtuplePerDetector true
/RMG/Output/NtupleUseVolumeName true
/RMG/Output/Vertex/StorePrimaryParticleInformation
/RMG/Output/Scintillator/StoreParticleVelocities

/RMG/Generator/Confine UnConfined

/RMG/Generator/Select GPS
/gps/position 0 0 0
/gps/ang/type iso
/gps/particle gamma
/gps/energy 200 keV

/run/beamOn 50
