/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 1

/RMG/Processes/OpticalPhysics true
/run/initialize

#/process/optical/boundary/verbose 2

/RMG/Output/NtuplePerDetector false

/RMG/Detectors/Optical/UseQuantumEfficiency true
/RMG/Detectors/Optical/SetQEFile datasheets/R7081_QEWhitespace.csv

/RMG/Generator/Confine UnConfined
/RMG/Generator/Select MUSUNCosmicMuons

/RMG/Generator/MUSUNCosmicMuons/SetMUSUNFile MUSUN/MUSUN_100_events.csv

/run/beamOn 100
