/RMG/Geometry/GDMLDisableOverlapCheck true
/RMG/Processes/HadronicPhysics Shielding
/RMG/Manager/Randomization/Seed 1234

/RMG/Geometry/RegisterDetector Optical material 001 # workaround to get the vertexoutputscheme

/RMG/Output/ActivateOutputScheme Track
/RMG/Output/ActivateOutputScheme ParticleFilter

/run/initialize

/process/inactivate hadElastic neutron
/process/inactivate neutronInelastic neutron
/process/inactivate nFission neutron
/process/inactivate Decay neutron
/process/inactivate Transportation neutron

/RMG/Output/ParticleFilter/AddParticle 11

/RMG/Output/Track/AddProcessFilter nCapture
/RMG/Output/Vertex/StorePrimaryParticleInformation true

/RMG/Processes/Stepping/DaughterNucleusMaxLifetime 1 ps

/RMG/Generator/Select GPS
/gps/particle neutron
/gps/ene/type Pow
/gps/ene/min 0.01 eV
/gps/ene/max 1 MeV
/gps/ene/alpha -1 # Create log-uniform distribution
/gps/ang/type iso


/run/beamOn 100000
