/RMG/Geometry/GDMLDisableOverlapCheck true
/RMG/Processes/HadronicPhysics Shielding
/RMG/Manager/Randomization/Seed 1234

/RMG/Output/ActivateOutputScheme Track
/RMG/Output/ActivateOutputScheme ParticleFilter

/run/initialize

/process/inactivate hadElastic neutron
/process/inactivate neutronInelastic neutron
/process/inactivate nFission neutron
/process/inactivate Decay neutron
/process/inactivate Transportation neutron

/RMG/Output/ParticleFilter/AddParticle 11

/RMG/Output/Track/AddProcessFilter nCapture

/RMG/Processes/Stepping/DaughterNucleusMaxLifetime 1 ps

/RMG/Generator/Select GPS
/gps/particle neutron
/gps/energy 0.1 eV
/gps/ang/type iso


/run/beamOn 10000
