/RMG/Geometry/GDMLDisableOverlapCheck true
/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/UseGrabmayrsGammaCascades true
/RMG/Manager/Randomization/Seed 1234

/RMG/Output/ActivateOutputScheme Track
/RMG/Output/ActivateOutputScheme ParticleFilter

/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 155 data/156Gd-100Entries.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 157 data/158Gd-100Entries.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeRandomStartLocation 1
/run/initialize

/process/inactivate hadElastic neutron
/process/inactivate neutronInelastic neutron
/process/inactivate nFission neutron
/process/inactivate Decay neutron
/process/inactivate Transportation neutron

/RMG/Output/ParticleFilter/AddParticle 11

/RMG/Output/Track/AddProcessFilter RMGnCapture

/RMG/Processes/Stepping/DaughterNucleusMaxLifetime 1 ps

/RMG/Generator/Select GPS
/gps/particle neutron
/gps/energy 0.1 eV
/gps/ang/type iso


/run/beamOn 10000
