/RMG/Geometry/RegisterDetector Germanium target 001

/RMG/Geometry/SetMaxStepSize {MAX_STEP_SIZE_IN_M} m target

/run/initialize

# we don't want want multiple scattering, it's going to make it hard to compare
# to the theoretical range
/process/inactivate msc

/RMG/Output/Germanium/StoreTrackID true

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Geometrical/AddSolid Sphere
/RMG/Generator/Confinement/Geometrical/Sphere/OuterRadius 1

/RMG/Generator/Confinement/Geometrical/CenterPositionX 0
/RMG/Generator/Confinement/Geometrical/CenterPositionY 0
/RMG/Generator/Confinement/Geometrical/CenterPositionZ 0

/RMG/Generator/Select GPS
/gps/particle e-
/gps/ang/type iso
/gps/energy {ENERGY} keV

/run/beamOn {EVENTS}
