# /RMG/Manager/Logging/LogLevelScreen debug

/run/initialize

/RMG/Output/FileName output.root

# /RMG/Geometry/PrintListOfLogicalVolumes
# /RMG/Geometry/PrintListOfPhysicalVolumes

# /RMG/Generator/Select BxDecay0
# /bxdecay0/generator/dbd Ge76 2345 1 0

/RMG/Generator/Select GPS
/gps/particle ion
/gps/ion 27 60
/gps/energy 0 eV

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume HPGe

/run/beamOn 100
