/RMG/Manager/Logging/LogLevelScreen summary

/run/initialize

# /RMG/Geometry/PrintListOfLogicalVolumes
# /RMG/Geometry/PrintListOfPhysicalVolumes

# /RMG/Generator/Select BxDecay0
# /bxdecay0/generator/dbd Ge76 2345 1 0

/RMG/Generator/Select G4gun
/gun/particle ion
/gun/ion 27 60
/gun/energy 0 eV

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume HPGe

/run/beamOn 100000
