/RMG/Geometry/GDMLDisableOverlapCheck true

/RMG/Output/ActivateOutputScheme Track
/RMG/Output/ActivateOutputScheme ParticleFilter

/run/initialize

/RMG/Output/ParticleFilter/AddParticle 1000020040

/RMG/Generator/Confine UnConfined

/RMG/Generator/Select GPS
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 0.5 m
/gps/particle     ion
/gps/ion          90 228
/gps/energy       0 keV
/gps/ang/type     iso

/run/beamOn 10
