/control/execute vis.mac

/RMG/Generator/Confine Volume

# /RMG/Generator/Confinement/SampleOnSurface

/RMG/Generator/Confinement/Geometrical/AddSolid Sphere
/RMG/Generator/Confinement/Geometrical/CenterPositionX 0 m
/RMG/Generator/Confinement/Geometrical/CenterPositionY 2 m
/RMG/Generator/Confinement/Geometrical/CenterPositionZ 2 m
/RMG/Generator/Confinement/Geometrical/Sphere/InnerRadius 0 m
/RMG/Generator/Confinement/Geometrical/Sphere/OuterRadius 0.7 m

/RMG/Generator/Confinement/Physical/AddVolume Sphere
/RMG/Generator/Confinement/Physical/AddVolume BoxAndOrb

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 1 eV

/run/beamOn 2000
