/control/execute vis.mac

/RMG/Generator/Confine Volume

# /RMG/Generator/Confinement/SampleOnSurface

/RMG/Generator/Confinement/Geometrical/AddSolid Sphere
/RMG/Generator/Confinement/Geometrical/CenterPositionX 0 m
/RMG/Generator/Confinement/Geometrical/CenterPositionY 2 m
/RMG/Generator/Confinement/Geometrical/CenterPositionZ 2 m

/RMG/Generator/Confinement/Geometrical/Sphere/InnerRadius 0 m
/RMG/Generator/Confinement/Geometrical/Sphere/OuterRadius 0.7 m

/RMG/Generator/Confinement/Geometrical/AddSolid Cylinder
/RMG/Generator/Confinement/Geometrical/CenterPositionX -2 m
/RMG/Generator/Confinement/Geometrical/CenterPositionY -2 m
/RMG/Generator/Confinement/Geometrical/CenterPositionZ -2 m

/RMG/Generator/Confinement/Geometrical/Cylinder/InnerRadius 0.4 m
/RMG/Generator/Confinement/Geometrical/Cylinder/OuterRadius 0.7 m
/RMG/Generator/Confinement/Geometrical/Cylinder/Height 1.0 m
/RMG/Generator/Confinement/Geometrical/Cylinder/StartingAngle 45 deg
/RMG/Generator/Confinement/Geometrical/Cylinder/SpanningAngle 170 deg

/RMG/Generator/Confinement/Geometrical/AddSolid Box
/RMG/Generator/Confinement/Geometrical/CenterPositionX 0 m
/RMG/Generator/Confinement/Geometrical/CenterPositionY 0 m
/RMG/Generator/Confinement/Geometrical/CenterPositionZ -2 m

/RMG/Generator/Confinement/Geometrical/Box/XLength 0.7 m
/RMG/Generator/Confinement/Geometrical/Box/YLength 0.5 m
/RMG/Generator/Confinement/Geometrical/Box/ZLength 1.2 m

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 1 eV

/run/beamOn 5000
