/run/initialize

/RMG/Manager/Logging/LogLevelScreen detail

/vis/open OIQt
/vis/drawVolume
/vis/sceneHandler/attach

# /vis/viewer/set/defaultColour black
# /vis/viewer/set/background white
/vis/scene/add/axes 0 0 0 3 m

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
