/run/initialize

/vis/open OIQt
/vis/drawVolume
/vis/sceneHandler/attach

# /vis/viewer/set/defaultColour black
# /vis/viewer/set/background white

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume Box

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 1 eV

/run/beamOn 500
