/RMG/Geometry/RegisterDetector Germanium germanium 001

/run/initialize

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Geometrical/AddSolid Sphere
/RMG/Generator/Confinement/Geometrical/Sphere/OuterRadius 10

/RMG/Generator/Confinement/Geometrical/CenterPositionX 0
/RMG/Generator/Confinement/Geometrical/CenterPositionY 0
/RMG/Generator/Confinement/Geometrical/CenterPositionZ 0

/RMG/Generator/Select GPS
/gps/particle e-
/gps/ang/type iso
/gps/energy 1000 keV

/run/beamOn 10000
