/control/execute macros/_init.mac

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/ForceContainmentCheck true
/RMG/Generator/Confinement/SampleOnSurface true
/RMG/Generator/Confinement/SurfaceSampleMaxIntersections 6

/RMG/Generator/Confinement/Physical/AddVolume BoxWithHole
/RMG/Generator/Confinement/Physical/AddVolume BoxAndOrb
#/RMG/Generator/Confinement/Physical/AddVolume MotherOrb
/RMG/Generator/Confinement/Physical/AddVolume Polycone

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 1 eV

/run/beamOn 5000

/control/alias export-fn complex-surface.output
