/control/execute macros/vis.mac

/RMG/Generator/Confine Volume

/RMG/Generator/Confinement/Physical/AddVolume BoxWithHole
/RMG/Generator/Confinement/Physical/AddVolume BoxAndOrb
/RMG/Generator/Confinement/Physical/AddVolume MotherOrb
/RMG/Generator/Confinement/Physical/AddVolume Polycone
# /RMG/Generator/Confinement/Physical/AddVolume BoxAndOrb2

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 1 eV

/run/beamOn 5000

/vis/ogl/export complex-volume.pdf
