/control/execute macros/_init.mac

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/ForceContainmentCheck true

/RMG/Generator/Confinement/SamplingMode IntersectPhysicalWithGeometrical

/RMG/Generator/Confinement/Geometrical/AddSolid Sphere
/RMG/Generator/Confinement/Geometrical/CenterPositionX 1.5 m
/RMG/Generator/Confinement/Geometrical/CenterPositionY 2 m
/RMG/Generator/Confinement/Geometrical/CenterPositionZ 2 m
/RMG/Generator/Confinement/Geometrical/Sphere/InnerRadius 0 m
/RMG/Generator/Confinement/Geometrical/Sphere/OuterRadius 0.4 m

/RMG/Generator/Confinement/Physical/AddVolume MotherOrb

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 1 eV

/run/beamOn 2000

/control/alias export-fn geometrical-and-physical.output
