name: CI

on:
  push:
    branches:
      - main
      - "releases/**"
    paths-ignore:
      - "**.md"
  pull_request:
  release:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_on_linux:
    name: Test on remage image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # guideline: only test on latest patch releases (and maybe previous one)
        container_version:
          - G4.11.3
          - G4.11.2
          - slim

    container: docker://gipert/remage-base:${{ matrix.container_version }}

    steps:
      - uses: actions/checkout@v4
        with:
          # we need a fully checked-out repo to get version from setuptools-scm.
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request && github.event.pull_request.head.sha || github.ref }}

      - name: Build project
        run: |
          git config --global --add safe.directory $(pwd)  # make git work inside container.
          mkdir build
          cd build
          cmake -DRMG_BUILD_DOCS=OFF .. | tee -a build.log
          make | tee -a build.log
          make install | tee -a build.log

      - name: check version equality
        run: |
          cd build
          cpp_version=$(sed -En "s/-- remage version [0-9.]+ \(([0-9a-z.+_-]+)\)/\\1/p" build.log)
          py_version=$(sed -En "s/-- Installed python wrapper Version: ([0-9a-z.+_-]+)/\\1/p" build.log)
          if [ "$cpp_version" != "$py_version" ]; then
            echo "::error::version numbers of python wrapper ($py_version) and cpp executable ($cpp_version) differ!"
            exit 1
          else
            echo "::notice::version numbers of python wrapper ($py_version) and cpp executable ($cpp_version) are matching!"
          fi

      - name: Compare checked-in doc dump with current result
        if: ${{ matrix.container_version != 'slim' }}
        id: rmg_doc_dump
        continue-on-error: true
        run: |
          cd build
          cp ../docs/rmg-commands.md ../docs/rmg-commands.md.bak

          echo "::group::compile and run remage-doc-dump"
          make remage-doc-dump
          echo "::endgroup::"

          echo "::group::full generated command docs"
          cat -v ../docs/rmg-commands.md
          echo "::endgroup::"

          docs_differ=0
          docs_diff=$(diff -u ../docs/rmg-commands.md ../docs/rmg-commands.md.bak) || docs_differ=$?
          if [ $docs_differ -ne 0 ]; then
            echo "::error file=docs/rmg-commands.md::docs/rmg-commands.md is not up-to-date with remage source. please run 'make remage-doc-dump' and commit changes."
            echo "$docs_diff"
          else
            echo "::notice::docs/rmg-commands.md is up-to-date with remage source"
          fi

      - name: Setup and start xvfb (enables Geant4 visualization)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run full test suite
        if: ${{ matrix.container_version != 'slim' }}
        env:
          DISPLAY: :99
        run: |
          exit 0
          cd build
          ctest --output-on-failure

      - name: Upload test suite outputs to GitHub
        if: ${{ always() && matrix.container_version != 'slim' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-output-${{ matrix.container_version }}
          # artifacts must have a ".output*" extension
          path: build/tests/**/*.output*.*

      - name: Run minimal test suite
        if: ${{ matrix.container_version == 'slim' }}
        env:
          DISPLAY: :99
        run: |
          exit 0
          cd build
          ctest --output-on-failure --label-exclude 'extra|vis'

      - name: Compare checked-in doc dump with current result (2)
        if: ${{ matrix.container_version != 'slim' }}
        env:
          RESULT: ${{ steps.rmg_doc_dump.outcome }}
        run: |
          if [ "$RESULT" = "failure"" ]; then
            echo "::error file=docs/rmg-commands.md::docs/rmg-commands.md is not up-to-date with remage source. please run 'make remage-doc-dump' and commit changes."
            exit 1
          else
            echo "::notice::docs/rmg-commands.md is up-to-date with remage source"
          fi

# vim: expandtab tabstop=2 shiftwidth=2
